### ISSUE TITLE
unable to install jpegtran-cffi

### ISSUE THREAD

**Issue by schmocker** [NaturalHistoryMuseum/iiif-image-server#7]
Hi

I am currently looking for a IIIF solution to display 12k drone images in a web app. Since we already use FastAPI in other projects I find your solution very nice. Unfortunately I am not able to run this API since I am not able to install jpegtran-cffi on my mac. I also tried to add a Dockerfile to Build it from python:3.9.5 but I had problems installing jpegtran-cffi there to.

Can you tell me how you installed  jpegtran-cffi? If I'm able to create a runnable Dockerfile I am happy to contribute it to this repo.

BR

**Comment by jrdh** [comment]
Hey @schmocker, jpegtran-cffi can be a pain to install, unfortunately. The main problem I always come across is that you have to install cffi (i.e. `pip install cffi`) _before_ you then install jpegtran-cffi (i.e. `pip install jpegtran-cffi`). It doesn't seem to depend on it so pip just doesn't install it even though it's required.

We've got a docker image of this API in a private repo which unfortunately I can't share with you directly, however, I can make a copy of the Dockerfile here for others to use including yourself! Hopefully that'll help :)

**Comment by jrdh** [comment]
@schmocker - I've added a Dockerfile to the root of the repo with an example config etc in the `docker/` dir. It's definitely not perfect but it should work!
